import type { ReactNode } from "react";
import { Icon, type IconName } from "@/components/icons";

export function Button({ children, variant = "primary" }: { children: ReactNode; variant?: "primary" | "secondary" | "quiet" | "danger" }) { const styles = { primary: "bg-fair-blue text-white hover:bg-fair-blue-hover border-fair-blue", secondary: "bg-white text-slate-700 hover:bg-slate-50 border-slate-300", quiet: "bg-transparent text-slate-600 hover:bg-slate-100 border-transparent", danger: "bg-white text-red-700 hover:bg-red-50 border-red-200" }; return <button type="button" className={`inline-flex h-9 items-center justify-center gap-2 rounded-lg border px-3.5 text-sm font-semibold transition-colors ${styles[variant]}`}>{children}</button>; }
export function SectionCard({ title, description, action, children, className = "" }: { title?: string; description?: string; action?: ReactNode; children: ReactNode; className?: string }) { return <section className={`overflow-hidden rounded-xl border border-slate-200 bg-white ${className}`}>{(title || action) && <div className="flex items-start justify-between gap-4 border-b border-slate-200 px-5 py-4"><div>{title && <h2 className="font-semibold text-slate-950">{title}</h2>}{description && <p className="mt-1 text-xs leading-5 text-slate-500">{description}</p>}</div>{action}</div>}{children}</section>; }
export function MetricCard({ label, value, children, icon }: { label: string; value: string; children: ReactNode; icon: IconName }) { return <article className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><p className="text-sm font-medium text-slate-600">{label}</p><span className="grid size-8 place-items-center rounded-lg bg-blue-50 text-blue-600"><Icon name={icon}/></span></div><p className="mt-4 text-3xl font-semibold tracking-[-0.03em] text-slate-950">{value}</p><div className="mt-4 border-t border-slate-100 pt-3 text-xs leading-5 text-slate-500">{children}</div></article>; }
export type TruthState = "verified" | "conflict" | "fragmented" | "review";
export function StatusBadge({ state, label }: { state: TruthState; label?: string }) { const values = { verified: { text: label ?? "Verified", style: "bg-green-50 text-green-700 ring-green-200", icon: "check" as IconName }, conflict: { text: label ?? "Conflict", style: "bg-amber-50 text-amber-700 ring-amber-200", icon: "alert" as IconName }, fragmented: { text: label ?? "Source Fragmentation", style: "bg-orange-50 text-orange-700 ring-orange-200", icon: "link" as IconName }, review: { text: label ?? "Needs Review", style: "bg-slate-100 text-slate-600 ring-slate-200", icon: "clock" as IconName } }; const item = values[state]; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset ${item.style}`}><Icon name={item.icon} className="size-3.5"/>{item.text}</span>; }
export function FilterBar({ filters = ["Last 30 days", "All platforms", "All locations", "All audiences", "All categories"] }: { filters?: string[] }) { const icons: IconName[] = ["calendar", "platform", "pin", "users", "filter"]; return <div className="fair-scrollbar flex gap-2 overflow-x-auto border-b border-slate-200 bg-white px-5 py-3">{filters.map((filter, index) => <button type="button" key={filter} className="inline-flex h-9 shrink-0 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-xs font-medium text-slate-700 hover:bg-slate-50"><Icon name={icons[index] ?? "filter"}/>{filter}<span className="text-slate-400">⌄</span></button>)}</div>; }
export function ProgressBar({ value, color = "blue" }: { value: number; color?: "blue" | "green" | "amber" }) { const colors = { blue: "bg-blue-600", green: "bg-green-600", amber: "bg-amber-500" }; return <div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${colors[color]}`} style={{ width: `${value}%` }}/></div>; }
export function FairInsight({ observation, evidence, action }: { observation: string; evidence: string; action?: string }) { return <article className="rounded-xl border border-blue-200 bg-blue-50/50 p-5"><div className="flex items-center gap-2 text-blue-700"><span className="grid size-7 place-items-center rounded-md bg-blue-600 text-white"><Icon name="spark" className="size-4"/></span><span className="text-xs font-bold uppercase tracking-[.12em]">FAIR Insight</span></div><p className="mt-4 text-base font-semibold leading-6 text-slate-950">{observation}</p><div className="mt-4 rounded-lg border border-blue-100 bg-white p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Evidence</p><p className="mt-1 text-sm text-slate-700">{evidence}</p></div>{action && <p className="mt-3 text-sm text-slate-600"><span className="font-semibold text-slate-800">Recommended action:</span> {action}</p>}<button type="button" className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-blue-700 hover:text-blue-800">View analysis <Icon name="arrow" className="size-4"/></button></article>; }
export function MiniStat({ label, value, tone = "default" }: { label: string; value: string; tone?: "default" | "green" | "amber" | "blue" }) { const tones = { default: "text-slate-950", green: "text-green-700", amber: "text-amber-700", blue: "text-blue-700" }; return <div><p className={`text-lg font-semibold ${tones[tone]}`}>{value}</p><p className="mt-0.5 text-xs text-slate-500">{label}</p></div>; }
