import type { Metadata } from "next";
import { PageHeader } from "@/components/page-header";
import { Button, FilterBar, MiniStat, ProgressBar, SectionCard, StatusBadge } from "@/components/ui";
import { Icon } from "@/components/icons";
export const metadata: Metadata = { title: "AI Monitor" };
const steps = ["Generating customer queries", "Testing AI responses", "Checking business visibility", "Extracting factual claims", "Comparing against verified truth", "Generating insights"];
export default function MonitoringPage() { return <><PageHeader title="AI Monitor" description="Run and inspect operational checks across AI search experiences." action={<Button><Icon name="play"/>Run new scan</Button>}/><FilterBar filters={["Latest run", "All platforms", "All locations", "All categories"]}/><main className="space-y-5 bg-[#f8fafc] p-5 lg:p-7">
  <div className="grid gap-4 xl:grid-cols-[1.4fr_1fr]"><SectionCard title="Latest monitoring run" description="September 29, 2026 at 2:42 PM" action={<StatusBadge state="verified" label="Completed"/>}><div className="p-5"><div className="mb-5 flex items-center justify-between"><span className="text-sm font-medium text-slate-700">Scan complete</span><span className="text-sm font-semibold text-blue-700">100%</span></div><ProgressBar value={100}/><div className="mt-6 grid gap-2 sm:grid-cols-2">{steps.map(step => <div key={step} className="flex items-center gap-2 rounded-lg bg-slate-50 p-3 text-xs font-medium text-slate-700"><span className="grid size-5 place-items-center rounded-full bg-green-100 text-green-700"><Icon name="check" className="size-3"/></span>{step}</div>)}</div></div></SectionCard><SectionCard title="Run summary" description="Results from 86 benchmark queries"><div className="grid grid-cols-2 gap-y-6 p-5"><MiniStat label="Queries tested" value="86"/><MiniStat label="AI responses" value="86"/><MiniStat label="Business mentioned" value="71" tone="blue"/><MiniStat label="Extracted claims" value="47"/><MiniStat label="Detected conflicts" value="4" tone="amber"/><MiniStat label="Avg. position" value="2.3"/></div></SectionCard></div>
  <SectionCard title="Recent AI responses" description="Visibility, recommendation position, and truth checks from the latest run"><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Query</th><th>Platform</th><th>Mentioned</th><th>Position</th><th>Claims</th><th>Truth status</th></tr></thead><tbody>{[["Best late-night food near campus","ChatGPT","Yes","#1","3","verified"],["Affordable dinner open after 10","Gemini","Yes","#3","2","conflict"],["Vegetarian food near the university","Perplexity","No","—","0","review"],["Best surf and turf burrito","ChatGPT","Yes","#2","4","verified"]].map(row => <tr key={row[0]}><td className="max-w-80 font-semibold text-slate-800">{row[0]}</td><td>{row[1]}</td><td className={row[2] === "Yes" ? "font-medium text-green-700" : "text-slate-500"}>{row[2]}</td><td>{row[3]}</td><td>{row[4]}</td><td><StatusBadge state={row[5] as "verified"|"conflict"|"review"}/></td></tr>)}</tbody></table></div></SectionCard>
</main></>; }
