import type { Metadata } from "next";
import { PageHeader } from "@/components/page-header";
import { Button, FilterBar, SectionCard, StatusBadge } from "@/components/ui";
export const metadata: Metadata = { title: "Human Review" };
const reviews = [
  { title: "Replace outdated menu source", context: "Incorrect hours and prices are appearing in AI responses.", recommendation: "Remove old_menu.pdf from public access and publish the current information on the business website.", evidence: "4 conflicts across 7 queries trace back to this document.", priority: "High" },
  { title: "Clarify delivery coverage", context: "AI systems report two different delivery radiuses.", recommendation: "Confirm the active delivery radius and add it to the verified Truth Profile.", evidence: "2 benchmark queries return 10 miles; current verified value is 5 miles.", priority: "Medium" },
];
export default function HumanReviewPage() { return <><PageHeader title="Human Review" description="Approve, refine, or dismiss FAIR-generated recommendations."/><FilterBar filters={["Waiting for review", "All priorities", "All issue types"]}/><main className="space-y-4 bg-[#f8fafc] p-5 lg:p-7">{reviews.map(review => <SectionCard key={review.title}><div className="p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-base font-semibold text-slate-950">{review.title}</h2><StatusBadge state="review" label="Waiting for review"/></div><p className="mt-2 text-sm text-slate-500">{review.context}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${review.priority === "High" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{review.priority} priority</span></div><div className="mt-5 grid gap-3 lg:grid-cols-2"><div className="rounded-lg border border-blue-100 bg-blue-50/50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-blue-700">FAIR recommendation</p><p className="mt-2 text-sm font-medium leading-6 text-slate-800">{review.recommendation}</p></div><div className="rounded-lg border border-slate-200 bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Supporting evidence</p><p className="mt-2 text-sm leading-6 text-slate-700">{review.evidence}</p></div></div><div className="mt-5 flex flex-wrap justify-end gap-2"><Button variant="quiet">Dismiss</Button><Button variant="secondary">Modify</Button><Button>Approve</Button></div></div></SectionCard>)}</main></>; }
